# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:

  build:
    docker:
      - image: circleci/golang:1.12
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build source image
        command: |
          docker build -t $CIRCLE_PROJECT_REPONAME:$(git rev-parse --short HEAD) .
    - run:
        name: Save image
        command: |
          mkdir -p /tmp/build/docker/
          docker save -o /tmp/build/docker/$CIRCLE_PROJECT_REPONAME-$(git rev-parse --short HEAD) $CIRCLE_PROJECT_REPONAME:$(git rev-parse --short HEAD)
          ls -lah /tmp/build/docker/
    - persist_to_workspace:
          root: /tmp/build
          paths:
            - docker/*

  push:
    docker:
      - image: circleci/golang:1.12
    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
          at: /tmp/build
    - run:
        name: Save image
        command: |
          docker load -i /tmp/build/docker/$CIRCLE_PROJECT_REPONAME-$(git rev-parse --short HEAD)
    - run: 
        name: DockerHub Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Tag images
        command: |
          docker tag $CIRCLE_PROJECT_REPONAME:$(git rev-parse --short HEAD) $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(git rev-parse --short HEAD)
          docker tag $CIRCLE_PROJECT_REPONAME:$(git rev-parse --short HEAD) $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:latest
    - run:
        name: Push to registry
        command: |
          docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(git rev-parse --short HEAD)
          docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  version: 2
  create-images:
    jobs:
      - build
      - push:
          requires:
          - build
          filters:
            branches:
              only: 
                - master